---
- hosts: all 

  tasks:
    - name: Disable Firewall
      service: name=ufw state=stopped

    - name: Install HTTPS Apt Packages
      apt: name={{ item }} update_cache=yes
      with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common

    - name: Add Docker GPG Key
      apt_key: url=https://download.docker.com/linux/ubuntu/gpg state=present

    - name: Add Docker Repository
      apt_repository:
        repo="deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state=present

    - name: Install Docker CE
      apt: name=docker-ce state=present update_cache=yes

    - name: Enable Docker at Startup
      service: name=docker state=started enabled=yes

    - name: add user mod to docker
      command: usermod -aG docker {{ ansible_user }}